#
# Configuration for staging environment
#
version: 1.0
app:
  # build id to deploy. if 'version' is commented out, the application is not deployed
  version: "0754daec-294e-45b0-a9ef-9c8e8c3ce35c"

  # DB2 service
  services:
    - type: Db2cloud
      name: Db2-nd-mei-easej
    
  # number of instances
  instances:
    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    max: 1
    
  resources:
    # max cpu. memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 4 gb
    cpu: 1

  # List of environment variables that are set for the application
  env:
    - name: JVM_ARGS 
      value: "-Xms=1024m"
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: DEV    

  # List of variables that can be referenced in the server.xml
  variables:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: OIDC_DISCOVERY_HOST
      value: "https://mei-easej-db2-academic-way-8529.staging.us-east.c2.appflow.dev.ibmappdomain.cloud/"
    - name: db2HostName
      value: "19af6446-6171-4641-8aba-9dcff8e1b6ff.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud"
    - name: db2Port
      value: "30699"
    - name: dbName
      value: "bludb"
    - name: db2UserName
      value: "easedb2user1"
      
